#!/bin/sh
docker run \
	--interactive \
	--tty \
	--rm \
	--cpus=3 \
	--memory=50GB \
	--memory-swap=-1 \
	--publish 8787:8787 \
	--env PASSWORD=password \
	--env ROOT=true \
	\
	--volume /Users/rainer/R/dockerlib:/opt/R/library \
	--env R_LIBS=/opt/R/library \
	--volume ./rsession.conf:/etc/rstudio/rsession.conf \
	\
	--volume /Users/rainer/R/rstudio:/home/rstudio/ \
	--volume /Users/rainer/Documents:/home/rstudio/Documents \
	--volume /Users/rainer/git:/home/rstudio/git \
	rocker/rstudio